services:
  backend:
    container_name: diagram-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - PORT=4000
      - FLASK_API_URL=http://diagram-flask:5001
      - REDIS_URL=redis://diagram-redis:6379
      - VIRTUAL_HOST=diagram.harshsaw.tech
      - LETSENCRYPT_HOST=diagram.harshsaw.tech
      - LETSENCRYPT_EMAIL=mister.harshkumar@gmail.com
    networks:
      - proxy

  diagram-flask:
    container_name: diagram-flask
    build:
      context: ./image-analysis-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./image-analysis-service:/app
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: nginx-network