networks:
  app-network:
    driver: bridge

services:
  backend:
    container_name: diagram-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules

    env_file:
      - ./backend/.env
    environment:
      - PORT=4000
      - FLASK_API_URL=http://diagram-flask:5000 

      - REDIS_URL=redis://diagram-redis:6379  # ✅ New Redis connection URL
    networks:
      - app-network
    

  diagram-flask:
    container_name: diagram-flask
    build:
      context: ./image-analysis-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./image-analysis-service:/app
    networks:
      - app-network
 





