
services:
  # Main backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: diagram-backend
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - REDIS_PORT=6379
      - FLASK_API_URL=http://image-analysis:5001
    depends_on:
      - redis
      - image-analysis
    networks:
      - diagram-network
    volumes:
      - ./logs:/app/logs

  # Image processing worker service
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: diagram-worker
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_API_URL=http://image-analysis:5001
    depends_on:
      - redis
      - image-analysis
    networks:
      - diagram-network
    volumes:
      - ./logs:/app/logs

  # Redis for queue management
  redis:
    image: redis:6-alpine
    container_name: diagram-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - diagram-network

  # Image analysis Flask service
  image-analysis:
    build:
      context: ./image-analysis-service
      dockerfile: Dockerfile
    container_name: diagram-flask
    restart: unless-stopped
    networks:
      - diagram-network
    volumes:
      - ./image-analysis-service/uploads:/app/uploads

# Persistent volumes
volumes:
  redis-data:

# Network configuration
networks:
  diagram-network:
    driver: bridge