

networks:
  app-network:
    driver: bridge

services:
  backend:
    container_name: diagram-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules

    env_file:
      - ./backend/.env
    environment:
      - PORT=4000
      - FLASK_API_URL=http://diagram-flask:5001  # ✅ Ensure it matches Flask service
      - DATABASE_URL=postgres://diagram:diagram123@diagram-postgres:5432/diagramdb

    networks:
      - app-network
    depends_on:
      - diagram-flask  # ✅ Must match Flask service

  diagram-flask:  # ✅ Ensure this matches what backend is calling
    container_name: diagram-flask
    build:
      context: ./image-analysis-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./image-analysis-service:/app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  diagram-postgres:
    container_name: diagram-postgres
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=diagram
      - POSTGRES_PASSWORD=diagram123
      - POSTGRES_DB=diagramdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data: