services:
  backend:
    container_name: diagram-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_API_URL=http://image-analysis:5001
    depends_on:
      - redis
      - image-analysis
    networks:
      - diagram-network
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
 

  worker:
    container_name: diagram-worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_API_URL=http://image-analysis:5001
    depends_on:
      - redis
      - image-analysis
    networks:
      - diagram-network
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  redis:
    container_name: diagram-redis
    image: redis:6-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    networks:
      - diagram-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  image-analysis:
    container_name: diagram-flask
    build:
      context: ./image-analysis-service
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - diagram-network
    volumes:
      - ./image-analysis-service/uploads:/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"



volumes:
  redis-data:

networks:
  diagram-network:
    driver: bridge
  nginx-network:
    external: true
    name: nginx-network